version: '3.8'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:6.0
    container_name: zxb-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - zxb-network

  # Redis 服务
  redis:
    image: redis:7.0
    container_name: zxb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - zxb-network

  # RabbitMQ 服务
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: zxb-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password123
    networks:
      - zxb-network

  # Elasticsearch 服务
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: zxb-elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - zxb-network

  # 后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zxb-backend
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:password123@rabbitmq:5672
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - elasticsearch
    networks:
      - zxb-network

  # 前端服务
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zxb-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - zxb-network

networks:
  zxb-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  elasticsearch_data: 